### ISSUE TITLE
steganography.live is down

### ISSUE THREAD

**Issue by flarn2006** [harvardnlp/NeuralSteganography#2]
Not sure if this falls within the scope of this repository's issues, but I wasn't sure where else to put it.

I've tried from multiple locations so I know it's not just my Internet connection or ISP.

**Comment by da03** [comment]
Fixed. Thanks for noting that!

**Comment by flarn2006** [comment]
You're welcome! Out of curiosity, what was the problem?

**Comment by flarn2006** [comment]
It's down again

**Comment by flarn2006** [comment]
Down again.

Let me know if you'd prefer I didn't post here every time.

Also in case you're wondering why I'm using the site so much, I have a lot of fun with it, just reading the text it generates. :D

**Comment by flarn2006** [comment]
Down once again :/

**Comment by da03** [comment]
Thanks for keeping an eye on our website! We have some problems with our server, but we'll bring it back once our server gets fixed.

**Comment by da03** [comment]
fixed

**Comment by flarn2006** [comment]
Thanks :)

If it ever needs to go down permanently, can you post the code for the site
somewhere? The security concern won't be an issue then, and that way I can
continue using it with the interface I'm used to, including the userscript
I created to make it more convenient for the way I use the site.

(I'm curious, is there anyone else you know of who uses the site as I do,
just as a random text generator? It really is a lot of fun. :D )

**Comment by flarn2006** [comment]
Down again

**Comment by da03** [comment]
Thanks for noticing this. FIxed now.

**Comment by flarn2006** [comment]
Guess what 😛

**Comment by da03** [comment]
lol thanks for keeping an eye on this! Fixed.

**Comment by silentsilas** [comment]
Down again. I'd also be interested in the code for the site to be open source'd so that people can self-host.

**Comment by flarn2006** [comment]
It's either down again or still down from before; I'm not sure how long.

**Comment by marakortenkamp** [comment]
Hi, it seems to be down again.

**Comment by da03** [comment]
thanks for reporting that! It's fixed now.

**Comment by marakortenkamp** [comment]
it's down again 😬

**Comment by da03** [comment]
lol thanks for notifying us! It's back now. (we are using a Harvard cluster which reboots every few weeks)
